import React, { useEffect, useState } from 'react'

import './TermCondition.css'
import Header from '../../components/Header/Header'
import Footer from '../../components/Footer/Footer'
import LinkSend from '../../components/LinkSend/LinkSend'
import { termService } from '../../services'

export default function TermCondition() {
  const [terms, setTerms] = useState();

  useEffect(() => {
    fetchTerms()
  }, [])

  const fetchTerms = () => {
    termService().then(res => {
      setTerms(res.data);
    }).catch(err => {
      console.log(err)
    })
  }
  return (
    <>

      <Header />

      <section className='pg-privacypolicy pb-4'>
        <div className='container'>
          <div className='bg-white py-4 shadow'>
            <div className='p-4 pg-privacypolicy-text' dangerouslySetInnerHTML={{ __html: terms && terms }} />


            {/* <div className='p-4 pg-privacypolicy-text'>
                <p>
                   <strong>Physics Galaxy Treams of use</strong>
                </p>
                <p>
                   This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                </p>
                <p>
                Membership Eligibility</p>
                <p>
                ACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING. By impliedly or expressly accepting these Terms of Use, You also accept and agree to be bound by Flipkart Policies ((including but not limited to Privacy Policy available at Privacy) as amended from time to time.
                </p>
               <p> Your Account and Registration Obligations</p>

              <p> If You use the Platform, You shall be responsible for maintaining the confidentiality of your Display Name and Password and You shall be responsible for all activities that occur under your Display Name and Password. You agree that if You provide any information that is untrue, inaccurate, not current or incomplete or We have reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or not in accordance with the this Terms of Use, We shall have the right to indefinitely suspend or terminate or block access of your membership on the Platform and refuse to provide You with access to the Platform.</p>
              
              <p>Henceforward:</p>
              <ol>
                <li>All commercial/contractual terms are offered by and agreed to between Buyers and Sellers alone. The commercial/contractual terms include without limitation price, shipping costs, payment methods, payment terms, date, period and mode of delivery, warranties related to products and services and after sales services related to products and services. Flipkart does not have any control or does not determine or advise or in any way involve itself in the offering or acceptance of such commercial/contractual terms between the Buyers and Sellers. All discounts, offers (including exchange offers) are by the Seller/Brand and not by Flipkart.</li>
                <li>Placement of order by a Buyer with Seller on the Platform is an offer to buy the product(s) in by the Buyer to the Seller and it shall not be construed as Seller's acceptance of Buyer's offer to buy the product(s) ordered. The Seller retains the right to cancel any such order placed by the Buyer, at its sole discretion and the Buyer shall be intimated of the same by way of an email/SMS. Any transaction price paid by Buyer in case of such cancellation by Seller, shall be refunded to the Buyer. Further, the Seller may cancel an order wherein the quantities exceed the typical individual consumption. This applies both to the number of products ordered within a single order and the placing of several orders for the same product where the individual orders comprise a quantity that exceeds the typical individual consumption. What comprises a typical individual's consumption quantity limit shall be based on various factors and at the sole discretion of the Seller and may vary from individual to individual.</li>
                <li>Flipkart does not make any representation or Warranty as to specifics (such as quality, value, salability, etc) of the products or services proposed to be sold or offered to be sold or purchased on the Platform. Flipkart does not implicitly or explicitly support or endorse the sale or purchase of any products or services on the Platform. Flipkart accepts no liability for any errors or omissions, whether on behalf of itself or third parties.</li>
                <li>Flipkart is not responsible for any non-performance or breach of any contract entered into between Buyers and Sellers. Flipkart cannot and does not guarantee that the concerned Buyers and/or Sellers will perform any transaction concluded on the Platform. Flipkart shall not and is not required to mediate or resolve any dispute or disagreement between Buyers and Sellers.</li>
                <li>Flipkart does not make any representation or warranty as to the item-specifics (such as legal title, creditworthiness, identity, etc) of any of its Users. You are advised to independently verify the bona fides of any particular User that You choose to deal with on the Platform and use Your best judgment in that behalf.</li>
                <li>Flipkart does not at any point of time during any transaction between Buyer and Seller on the Platform come into or take possession of any of the products or services offered by Seller nor does it at any point gain title to or have any rights or claims over the products or services offered by Seller to Buyer.</li>
                <li>At no time shall Flipkart hold any right, title or interest over the products nor shall Flipkart have any obligations or liabilities in respect of such contract entered into between Buyers and Sellers. Flipkart is not responsible for unsatisfactory or delayed performance of services or damages or delays as a result of products which are out of stock, unavailable or back ordered.</li>
                <li>The Platform is only a platform that can be utilized by Users to reach a larger base to buy and sell products or services. Flipkart is only providing a platform for communication and it is agreed that the contract for sale of any of the products or services shall be a strictly bipartite contract between the Seller and the Buyer.</li>
                </ol>

                <p>Charges</p>

                <p>Flipkart may charge a nominal fee for browsing and buying on the Platform. Flipkart reserves the right to change its Fee Policy from time to time. In particular, Flipkart may at its sole discretion introduce new services/fees and modify some or all of the existing services/fees offered on the Platform. In such an event, Flipkart reserves the right to introduce fees for the new services offered or amend/introduce fees for existing/new services, as the case may be. Changes to the Fee Policy shall be posted on the Platform and such changes shall automatically become effective immediately after they are posted on the Platform. Unless otherwise stated, all fees shall be quoted in Indian Rupees. You shall be solely responsible for compliance of all applicable laws including those in India for making payments to Flipkart Internet Private Limited.</p>

               <p> Use of the Platform</p>

               <p> You agree, undertake and confirm that Your use of Platform shall be strictly governed by the following binding principles:</p>

               <p> You shall not host, display, upload, modify, publish, transmit, update or share any information which:</p>
                <p>(a) belongs to another person and to which You do not have any right to;</p>

               <p> (b) is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic, libellous, invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever; or unlawfully threatening or unlawfully harassing including but not limited to "indecent representation of women" within the meaning of the Indecent Representation of Women (Prohibition) Act, 1986;</p>

               <p> (c) is misleading in any way;</p>

                <p>(d) is patently offensive to the online community, such as sexually explicit content, or content that promotes obscenity, paedophilia, racism, bigotry, hatred or physical harm of any kind against any group or individual;</p>

               <p> (e) harasses or advocates harassment of another person;</p>

               <p> (f) involves the transmission of "junk mail", "chain letters", or unsolicited mass mailing or "spamming";</p>

                <p>(g) promotes illegal activities or conduct that is abusive, threatening, obscene, defamatory or libellous;</p>

                <p>(h) infringes upon or violates any third party's rights [including, but not limited to, intellectual property rights, rights of privacy (including without limitation unauthorized disclosure of a person's name, email address, physical address or phone number) or rights of publicity];</p>

               <p> (i) promotes an illegal or unauthorized copy of another person's copyrighted work (see "Copyright complaint" below for instructions on how to lodge a complaint about uploaded copyrighted material), such as providing pirated computer programs or links to them, providing information to circumvent manufacture-installed copy-protect devices;</p>

               <p> (j) contains restricted or password-only access pages, or hidden pages or images (those not linked to or from another accessible page);</p>

                <p>(k) provides material that exploits people in a sexual, violent or otherwise inappropriate manner or solicits personal information from anyone;</p>

                <p>(l) provides instructional information about illegal activities such as making or buying illegal weapons, violating someone's privacy, or providing or creating computer viruses;</p>

                <p>(m) contains video, photographs, or images of another person (with a minor or an adult).</p>

                <p>(n) tries to gain unauthorized access or exceeds the scope of authorized access to the Platform or to profiles, blogs, communities, account information, bulletins, friend request, or other areas of the Platform or solicits passwords or personal identifying information for commercial or unlawful purposes from other users;</p>

                <p>(o) engages in commercial activities and/or sales without Our prior written consent such as contests, sweepstakes, barter, advertising and pyramid schemes, or the buying or selling of "virtual" products related to the Platform. Throughout this Terms of Use, Flipkart's prior written consent means a communication coming from Flipkart's Legal Department, specifically in response to Your request, and specifically addressing the activity or conduct for which You seek authorization;</p> 

                <p>(p) solicits gambling or engages in any gambling activity which We, in Our sole discretion, believes is or could be construed as being illegal;</p>

                <p>(q) interferes with another USER's use and enjoyment of the Platform or any other individual's User and enjoyment of similar services;</p>

                <p>(r) refers to any Platform or URL that, in Our sole discretion, contains material that is inappropriate for the Platform or any other Platform, contains content that would be prohibited or violates the letter or spirit of these Terms of Use.</p> 

                <p>(s) harm minors in any way;</p>

                <p>(t) infringes any patent, trademark, copyright or other proprietary rights or third party's trade secrets or rights of publicity or privacy or shall not be fraudulent or involve the sale of counterfeit or stolen products;</p>  

                <p>(u) violates any law for the time being in force;</p> 

                <p> (v) deceives or misleads the addressee/ users about the origin of such messages or communicates any information which is grossly offensive or menacing in nature;</p> 

                <p>(w) impersonate another person;</p>  

                <p>(x) contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource; or contains any trojan horses, worms, time bombs, cancelbots, easter eggs or other computer programming routines that may damage, detrimentally interfere with, diminish value of, surreptitiously intercept or expropriate any system, data or personal information;</p> 

                <p>(y) threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting any other nation.</p> 

                <p>(z) shall not be false, inaccurate or misleading;</p>
            </div> */}
          </div>
        </div>

      </section>

      <LinkSend />
      <Footer />

    </>
  )
}
